"""fullname field added

Revision ID: 710f73c16c12
Revises: a512821222b9
Create Date: 2017-06-04 02:57:58.125805

"""

# revision identifiers, used by Alembic.
revision = '710f73c16c12'
down_revision = 'a512821222b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
