"""removed username field

Revision ID: a512821222b9
Revises: e772aa6eb13c
Create Date: 2017-06-04 02:16:25.829467

"""

# revision identifiers, used by Alembic.
revision = 'a512821222b9'
down_revision = 'e772aa6eb13c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fitbitid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['fitbitid'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'fitbitid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
